config:
  project_repos:
    template-py:
      repo: https://github.com/BorjaEst/template-py.git
      branch: master 
      dockerhub: boressan/template-py
      dockertag: latest

sqa_criteria:
  qc_style:
    repos:
      template-py:
        container: testing
        tox:
          tox_file: /template-py/tox.ini
          testenv:
            - stylecheck
  qc_coverage:
    repos:
      template-py:
        container: testing
        tox:
          tox_file: /template-py/tox.ini
          testenv:
            - unittesting
  qc_functional:
    repos:
      template-py:
        container: testing
        tox:
          tox_file: /template-py/tox.ini
          testenv:
              - functional
  qc_security:
    repos:
      template-py:
        container: testing
        tox:
          tox_file: /template-py/tox.ini
          testenv:
            - bandit
  qc_doc:
    repos:
      template-py:
        container: testing
        tox:
          tox_file: /template-py/tox.ini
          testenv:
            - docs

#environment:
#  LANG: C.UTF-8

timeout: 900
